#!/usr/bin/exec-suid --real -- /usr/bin/python -I

import os
import socket
import subprocess
import time
from dojjail import Host, Network

flag = open("/flag").read()

class ClientHost(Host):
    def entrypoint(self):
        while True:
            try:
                client_socket = socket.socket()
                client_socket.connect(("10.0.0.3", 31337))
                client_socket.sendall(flag.encode())
                client_socket.close()
                time.sleep(1)
            except (ConnectionError, TimeoutError):
                continue

user_host = Host("ip-10-0-0-1")
client_host = ClientHost("ip-10-0-0-2")
network = Network(hosts={user_host: "10.0.0.1", client_host: "10.0.0.2"}, subnet="10.0.0.0/24")
network.run()

user_host.interact()
