#!/opt/pwn.college/python

import base64
from Crypto.Random import get_random_bytes
from Crypto.Util.strxor import strxor

flag = open("/flag", "rb").read()

key = get_random_bytes(len(flag))
ciphertext = strxor(flag, key)

print(f"your one time pad: {base64.b64encode(key).decode()}")
print(f"secret ciphertext: {base64.b64encode(ciphertext).decode()}")
