#!/opt/pwn.college/python

from base64 import b64encode
from Crypto.Random import get_random_bytes
from Crypto.Util.strxor import strxor

flag = open("/flag", "rb").read()

key = get_random_bytes(len(flag))
ciphertext = strxor(flag, key)

print(f"One-Time Pad Key (b64): {b64encode(key).decode()}")
print(f"Flag Ciphertext (b64): {b64encode(ciphertext).decode()}")
