#!/opt/pwn.college/python

import random
import sys

for n in range(10):
	print(f"Challenge number {n}...")

	key = random.randrange(1, 256)
	plain_secret = random.randrange(0, 256)
	cipher_secret = plain_secret ^ key

	print(f"The key: 0x{'%02x'%key}")
	print(f"Encrypted secret: 0x{'%02x'%cipher_secret}")
	answer = int(input("Decrypted secret? "), 16)
	print(f"You entered: 0x{'%02x'%answer}, decimal {answer}.")
	if answer == plain_secret:
		print("CORRECT! Your flag:")
		print(open("/flag").read())
	else:
		print("INCORRECT!")
		sys.exit(1)
