#!/opt/pwn.college/python

import base64
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
from Crypto.Random import get_random_bytes

flag = open("/flag", "rb").read()

key = get_random_bytes(16)
cipher = AES.new(key=key, mode=AES.MODE_ECB)
ciphertext = cipher.encrypt(pad(flag, cipher.block_size))

print(f"aes key: {base64.b64encode(key).decode()}")
print(f"secret ciphertext: {base64.b64encode(ciphertext).decode()}")
