#!/opt/pwn.college/python

from base64 import b64encode
from Crypto.PublicKey import RSA

flag = open("/flag", "rb").read()
assert len(flag) <= 256

key = RSA.generate(2048)
print(f"e = {key.e:#x}")
print(f"d = {key.d:#x}")
print(f"n = {key.n:#x}")

ciphertext = pow(int.from_bytes(flag, "little"), key.e, key.n).to_bytes(256, "little")
print(f"Flag Ciphertext (b64): {b64encode(ciphertext).decode()}")
