#!/opt/pwn.college/python

import flask
import os

app = flask.Flask(__name__)

@app.route("/", methods=["GET"])
def challenge_get():
    return f"""
        <html><body>
        <h1>pwnmsg ephemeral message service</h1>
        The message: {flask.request.args.get("msg", "(none)")}
        <hr><form>Craft a message:<input type=text name=msg><input type=submit value=Submit></form>
        </body></html>
    """

app.secret_key = os.urandom(8)
app.run("challenge.localhost", 8080 if os.geteuid() else 80)
