#!/opt/pwn.college/python

import subprocess
import datetime
import flask
import os

app = flask.Flask(__name__)

@app.route("/", methods=["GET", "POST"])
def challenge():
    timezone = flask.request.args.get("timezone", "MST")
    result = subprocess.run(
        f"TZ={timezone} date",  # the command to run
        shell=True,                 # use the shell to run this command
        stdout=subprocess.PIPE,     # capture the standard output
        stderr=subprocess.STDOUT,   # 2>&1
        encoding="latin"            # capture the resulting output as text
    )

    if result.returncode != 0:
        flask.abort(500, "Error while running `date`!")
    try:
        datetime.datetime.strptime(result.stdout.strip(), '%a %b %d %H:%M:%S %p %Z %Y')
    except ValueError:
        flask.abort(500, "Output of 'date' contains invalid data!")

    return f"""
        <html><body>
        Welcome to the timezone service! Please choose a timezone to get the time there.
        <form><input type=text name=timezone><input type=submit value=Submit></form>
        <hr>
        <b>Output of: TZ={timezone} date</b><br>
        <pre>{result.stdout}</pre>
        </body></html>
        """

app.secret_key = open("/flag").read().strip()
app.run("challenge.localhost", int(os.environ.get("HTTP_PORT", 80)))
