#!/opt/pwn.college/python

import base64
from Crypto.Random import get_random_bytes
from Crypto.Util.strxor import strxor

flag = open("/flag", "rb").read()

key = get_random_bytes(256)
ciphertext = strxor(flag, key[:len(flag)])
print(f"secret ciphertext: {base64.b64encode(ciphertext).decode()}")

while True:
    plaintext = base64.b64decode(input("plaintext (b64): "))
    ciphertext = strxor(plaintext, key[:len(plaintext)])
    print(f"ciphertext: {base64.b64encode(ciphertext).decode()}")
